### ISSUE TITLE
Puedes meterlo en un do/while para no devolver siempre un 0 en caso de error

### ISSUE THREAD

**Issue by lmagarin** [damian-miquel/Examen-Segundo-Trimestre#4]
https://github.com/damian-miquel/Examen-Segundo-Trimestre/blob/163c4a77cac8e09e05e84f5d6a1d6e540e369c6f/Java/Almacen/utiles/Teclado.java#L60

**Comment by damian-miquel** [comment]
https://github.com/damian-miquel/Examen-Segundo-Trimestre/blob/725a54113396e1733404cbe73a05bb0ecff10aec/Java/Almacen/utiles/Teclado.java#L94-L102

**Comment by lmagarin** [comment]
👍
